### PR TITLE
added_yes_no_question

### PR DESCRIPTION
**Pull request by munoztd0**
Added yes or no questions for client danger errors to be able to bypass them in local tests

### CODE REVIEW

**Comment by JohnCoene** [comment]
We should remove the `browser` calls.

Does `askYesNo` only work interactively (I.e.: `interactive()`)?

**Comment by munoztd0** [comment]
> We should remove the `browser` calls.
> 
> Does `askYesNo` only work interactively (I.e.: `interactive()`)?

Yes you are right! Whatabout menu() ?

**Comment by JohnCoene** [comment]
I generally just use `readline` but if what you have works, no need to change, I would just wrap that in `if(interactive())`

Although, as I write that, I'm not sure how that would work because technically a shiny server is never interactive()?

Hmmm

**Comment by munoztd0** [comment]
So yeah I changed it to menu() so it can actually work not interactively.. Does that work for you ?

**Comment by JohnCoene** [comment]
Using `menu()` within a shiny application throws an error on my end (not usable outside of an interactive environment). I might be missing something.

**Comment by munoztd0** [comment]
> Using `menu()` within a shiny application throws an error on my end (not usable outside of an interactive environment). I might be missing something.

Wrapped it in if(inteactive){} statements

**Comment by JohnCoene** [comment]
Thanks I'll test (I think this will never be true within Shiny)

**Comment by munoztd0** [comment]
> Thanks I'll test (I think this will never be true within Shiny)

Yeah but at least you can test your app by running the code snippet such as in #64

**Pull request merged**
